<?php
/**
 * MIME Types
 *
 * Project maintained map of file extension => accepted MIME types, used to
 * validate the content type reported by the browser when an attachment is
 * uploaded.
 *
 * This map is NOT an upload allow-list. Which extensions may be uploaded is
 * decided by the attachment extension settings; this file only answers the
 * question "if this extension is allowed, which content types are plausible
 * for it?". An extension that is not listed here is simply not MIME checked.
 *
 * The reported content type comes from the client and can be forged, so this
 * check is a usability filter and not a security boundary. Never rely on it
 * to keep dangerous files out.
 *
 * Do not edit this file to add your own extensions: copy
 * sample.mimetypes-custom.php to mimetypes-custom.php and add them there, so
 * your changes survive an upgrade.
 *
 * Several extensions accept application/octet-stream because browsers and
 * operating systems commonly report it for those formats. It is deliberately
 * not accepted for formats that are reliably typed, such as PDF and images.
 *
 * @package WikiDocs
 * @repository https://github.com/Zavy86/wikidocs
 */

return array(

  // documents
  "pdf"  => array("application/pdf"),
  "doc"  => array("application/msword"),
  "docx" => array("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
  "xls"  => array("application/vnd.ms-excel","application/excel","application/x-excel","application/x-msexcel"),
  "xlsx" => array("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
  "ppt"  => array("application/vnd.ms-powerpoint","application/powerpoint","application/x-mspowerpoint"),
  "pptx" => array("application/vnd.openxmlformats-officedocument.presentationml.presentation"),
  "odt"  => array("application/vnd.oasis.opendocument.text"),
  "ods"  => array("application/vnd.oasis.opendocument.spreadsheet"),
  "odp"  => array("application/vnd.oasis.opendocument.presentation"),
  "rtf"  => array("application/rtf","text/rtf"),
  "epub" => array("application/epub+zip","application/octet-stream"),

  // text
  "txt"  => array("text/plain"),
  "md"   => array("text/markdown","text/x-markdown","text/plain"),
  "csv"  => array("text/csv","application/csv","text/plain","application/vnd.ms-excel"),
  "json" => array("application/json","text/json","text/plain"),
  "xml"  => array("application/xml","text/xml"),

  // images
  "jpg"  => array("image/jpeg"),
  "jpeg" => array("image/jpeg"),
  "png"  => array("image/png"),
  "gif"  => array("image/gif"),
  "bmp"  => array("image/bmp","image/x-ms-bmp"),
  "webp" => array("image/webp"),
  "avif" => array("image/avif"),
  "tif"  => array("image/tiff"),
  "tiff" => array("image/tiff"),
  "svg"  => array("image/svg+xml"),

  // audio
  "mp3"  => array("audio/mpeg","audio/mp3"),
  "m4a"  => array("audio/mp4","audio/x-m4a"),
  "aac"  => array("audio/aac"),
  "wav"  => array("audio/wav","audio/x-wav","audio/wave"),
  "flac" => array("audio/flac","audio/x-flac"),
  "oga"  => array("audio/ogg"),
  "ogg"  => array("audio/ogg","application/ogg"),

  // video
  "mp4"  => array("video/mp4"),
  "m4v"  => array("video/mp4","video/x-m4v"),
  "webm" => array("video/webm"),
  "ogv"  => array("video/ogg"),
  "mov"  => array("video/quicktime"),
  "mkv"  => array("video/x-matroska"),
  "avi"  => array("video/x-msvideo","video/avi"),

  // archives
  "zip"  => array("application/zip","application/x-zip-compressed","application/zip-compressed","multipart/x-zip"),
  "7z"   => array("application/x-7z-compressed","application/octet-stream"),
  "rar"  => array("application/vnd.rar","application/x-rar-compressed","application/octet-stream"),
  "gz"   => array("application/gzip","application/x-gzip","application/octet-stream"),
  "bz2"  => array("application/x-bzip2","application/octet-stream"),
  "tar"  => array("application/x-tar","application/octet-stream")

);
