blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://github.com/Zavy86/WikiDocs/discussions/categories/ideas
    about: You can submit here your ideas for the next release.
  - name: Wiki|Docs
    url: https://wikidocs.app
    about: You can view the official website and try out a demo here.
