import { randomBytes } from 'node:crypto';
import { constants } from 'node:fs';
import { access, mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { type ChildProcessWithoutNullStreams, spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { app, BrowserWindow, dialog, ipcMain, Menu, safeStorage, type MenuItemConstructorOptions, type OpenDialogOptions } from 'electron';
import { RemoteServerConfig, SyncOrchestrator, SyncStatusState } from './sync-orchestrator';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY:string;
declare const SETTINGS_WINDOW_WEBPACK_ENTRY:string;
declare const SETTINGS_WINDOW_PRELOAD_WEBPACK_ENTRY:string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if ( require('electron-squirrel-startup') ) {
  app.quit();
}

type RuntimeConfig = {
  readonly datasetsPath:string;
  readonly secret:string;
};

type RuntimeArtifacts = {
  readonly backendEntryPath:string;
  readonly backendWorkingDirectory:string;
  readonly frontendPath:string;
};

type SaveRuntimeConfigResult = {
  readonly status:'relaunching' | 'cancelled';
};

const BACKEND_PORT = 3210;
const BACKEND_PREFIX = '/api';
const BACKEND_HOST = '127.0.0.1';
const BACKEND_BASE_URL = `http://${ BACKEND_HOST }:${ BACKEND_PORT }`;
const BACKEND_HEALTHCHECK_URL = `${ BACKEND_BASE_URL }${ BACKEND_PREFIX }/health`;
const RUNTIME_CONFIG_FILENAME = 'runtime.config.json';
const SYNC_CONFIG_FILENAME = 'sync.config.json';
const SECRET_MIN_LENGTH = 32;

let mainWindow:BrowserWindow | null = null;
let settingsWindow:BrowserWindow | null = null;
let backendProcess:ChildProcessWithoutNullStreams | null = null;
let appClosing = false;
let appRelaunching = false;
let backendCrashDialogOpen = false;
let currentRuntimeConfig:RuntimeConfig | null = null;

const syncOrchestrator = new SyncOrchestrator(BACKEND_BASE_URL);

function resolveRuntimeWindowIconPath():string | undefined {
  if ( process.platform === 'darwin' ) {
    return undefined;
  }
  const iconFile:string = process.platform === 'win32' ? 'app.ico' : 'app.png';
  if ( app.isPackaged ) {
    return join(process.resourcesPath, 'icons', iconFile);
  }
  const monorepoRoot:string = resolveMonorepoRoot();
  return join(monorepoRoot, 'desktop', 'assets', 'icons', iconFile);
}

function getRuntimeConfigPath():string {
  return join(app.getPath('userData'), RUNTIME_CONFIG_FILENAME);
}

function getSyncConfigPath():string {
  return join(app.getPath('userData'), SYNC_CONFIG_FILENAME);
}

function ensureSecretValid(secret:string):void {
  if ( secret.trim().length < SECRET_MIN_LENGTH ) {
    throw new Error(`Secret must be at least ${ SECRET_MIN_LENGTH } characters`);
  }
}

async function ensureDirectoryWritable(path:string):Promise<void> {
  const stats = await stat(path);
  if ( ! stats.isDirectory() ) {
    throw new Error(`Path <${ path }> is not a directory`);
  }
  await access(path, constants.W_OK);
}

function parseRuntimeConfig(value:unknown):RuntimeConfig {
  if ( typeof value !== 'object' || value === null ) {
    throw new Error('Malformed runtime config JSON object');
  }
  const candidate:Record<string, unknown> = value as Record<string, unknown>;
  if ( typeof candidate.datasetsPath !== 'string' || candidate.datasetsPath.trim().length === 0 ) {
    throw new Error('Invalid or missing "datasetsPath" in runtime config');
  }
  if ( typeof candidate.secret !== 'string' ) {
    throw new Error('Invalid or missing "secret" in runtime config');
  }
  ensureSecretValid(candidate.secret);
  return {
    datasetsPath: candidate.datasetsPath.trim(),
    secret: candidate.secret,
  };
}

async function readRuntimeConfig(filePath:string):Promise<RuntimeConfig | null> {
  try {
    const content:string = await readFile(filePath, 'utf8');
    return parseRuntimeConfig(JSON.parse(content));
  } catch ( error ) {
    const fsError:NodeJS.ErrnoException = error as NodeJS.ErrnoException;
    if ( fsError.code === 'ENOENT' ) {
      return null;
    }
    throw error;
  }
}

async function writeRuntimeConfig(filePath:string, config:RuntimeConfig):Promise<void> {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, JSON.stringify(config, null, 2), 'utf8');
}

function encryptSecret(plainText:string):string {
  if ( ! plainText ) { return ''; }
  if ( safeStorage.isEncryptionAvailable() ) {
    return safeStorage.encryptString(plainText).toString('base64');
  }
  return Buffer.from(plainText, 'utf8').toString('base64');
}

function decryptSecret(encryptedText:string):string {
  if ( ! encryptedText ) { return ''; }
  try {
    const buffer = Buffer.from(encryptedText, 'base64');
    if ( safeStorage.isEncryptionAvailable() ) {
      return safeStorage.decryptString(buffer);
    }
    return buffer.toString('utf8');
  } catch {
    return encryptedText;
  }
}

async function readSyncConfig():Promise<RemoteServerConfig> {
  const filePath:string = getSyncConfigPath();
  try {
    const content:string = await readFile(filePath, 'utf8');
    const parsed:unknown = JSON.parse(content);
    if ( typeof parsed !== 'object' || parsed === null ) {
      throw new Error('Malformed sync config');
    }
    const candidate:Record<string, unknown> = parsed as Record<string, unknown>;
    const rawPassword = typeof candidate.serverPassword === 'string' ? candidate.serverPassword : '';
    return {
      serverUrl: typeof candidate.serverUrl === 'string' ? candidate.serverUrl.trim() : '',
      serverAccount: typeof candidate.serverAccount === 'string' ? candidate.serverAccount.trim() : '',
      serverPassword: decryptSecret(rawPassword),
      autoSyncEnabled: Boolean(candidate.autoSyncEnabled),
      autoSyncIntervalMinutes: typeof candidate.autoSyncIntervalMinutes === 'number' ? candidate.autoSyncIntervalMinutes : 15,
    };
  } catch {
    return {
      serverUrl: '',
      serverAccount: '',
      serverPassword: '',
      autoSyncEnabled: false,
      autoSyncIntervalMinutes: 15,
    };
  }
}

async function writeSyncConfig(config:RemoteServerConfig):Promise<void> {
  const filePath:string = getSyncConfigPath();
  await mkdir(dirname(filePath), { recursive: true });
  const payload = {
    serverUrl: config.serverUrl.trim(),
    serverAccount: config.serverAccount.trim(),
    serverPassword: encryptSecret(config.serverPassword),
    autoSyncEnabled: Boolean(config.autoSyncEnabled),
    autoSyncIntervalMinutes: Math.max(1, config.autoSyncIntervalMinutes),
  };
  await writeFile(filePath, JSON.stringify(payload, null, 2), 'utf8');
}

async function normalizeAndValidateRuntimeConfig(candidate:RuntimeConfig):Promise<RuntimeConfig> {
  const normalized:RuntimeConfig = {
    datasetsPath: candidate.datasetsPath.trim(),
    secret: candidate.secret,
  };
  if ( normalized.datasetsPath.length === 0 ) {
    throw new Error('DATASETS directory cannot be empty');
  }
  ensureSecretValid(normalized.secret);
  await ensureDirectoryWritable(normalized.datasetsPath);
  return normalized;
}

async function promptForDatasetsPathOrExit():Promise<string> {
  const shouldPrompt = true;
  while ( shouldPrompt ) {
    const selection = await dialog.showOpenDialog({
      title: 'Select DATASETS directory',
      buttonLabel: 'Use this directory',
      properties: ['openDirectory'],
    });
    if ( selection.canceled || selection.filePaths.length === 0 ) {
      const { response } = await dialog.showMessageBox({
        type: 'warning',
        title: 'DATASETS required',
        message: 'Wiki|Docs needs a writable DATASETS directory to continue.',
        buttons: ['Select directory', 'Exit app'],
        defaultId: 0,
        cancelId: 1,
        noLink: true,
      });
      if ( response === 1 ) {
        throw new Error('Application closed because DATASETS directory was not selected');
      }
      continue;
    }
    const selected:string = selection.filePaths[ 0 ];
    try {
      await ensureDirectoryWritable(selected);
      return selected;
    } catch ( error ) {
      await dialog.showMessageBox({
        type: 'error',
        title: 'Invalid DATASETS directory',
        message: `Cannot use <${ selected }>.`,
        detail: error instanceof Error ? error.message : String(error),
        buttons: ['Select another directory'],
        defaultId: 0,
        cancelId: 0,
        noLink: true,
      });
    }
  }
  throw new Error('Dataset prompt loop ended unexpectedly');
}

async function ensureRuntimeConfigOrPrompt():Promise<RuntimeConfig> {
  const configPath:string = getRuntimeConfigPath();
  const existing:RuntimeConfig | null = await readRuntimeConfig(configPath);
  if ( existing ) {
    try {
      await ensureDirectoryWritable(existing.datasetsPath);
      return existing;
    } catch ( error ) {
      process.stderr.write(`Invalid datasetsPath in runtime config. Prompting for a new one. ${ String(error) }\n`);
    }
  }
  const datasetsPath:string = await promptForDatasetsPathOrExit();
  const config:RuntimeConfig = {
    datasetsPath,
    secret: randomBytes(48).toString('base64url'),
  };
  await writeRuntimeConfig(configPath, config);
  return config;
}

function resolveMonorepoRoot():string {
  return resolve(__dirname, '..', '..', '..');
}

function resolveRuntimeArtifacts():RuntimeArtifacts {
  if ( app.isPackaged ) {
    const resources:string = process.resourcesPath;
    return {
      backendEntryPath: join(resources, 'backend', 'src', 'main.js'),
      backendWorkingDirectory: resources,
      frontendPath: join(resources, 'browser'),
    };
  }
  const monorepoRoot:string = resolveMonorepoRoot();
  return {
    backendEntryPath: join(monorepoRoot, 'backend', 'dist', 'backend', 'src', 'main.js'),
    backendWorkingDirectory: join(monorepoRoot, 'backend'),
    frontendPath: join(monorepoRoot, 'frontend', 'dist', 'wikidocs-frontend', 'browser'),
  };
}

async function ensureRuntimeArtifactsPresent(artifacts:RuntimeArtifacts):Promise<void> {
  const backendStats = await stat(artifacts.backendEntryPath);
  if ( ! backendStats.isFile() ) {
    throw new Error(`Backend entrypoint not found: <${ artifacts.backendEntryPath }>`);
  }
  const frontendStats = await stat(artifacts.frontendPath);
  if ( ! frontendStats.isDirectory() ) {
    throw new Error(`Frontend directory not found: <${ artifacts.frontendPath }>`);
  }
  const frontendIndex:string = join(artifacts.frontendPath, 'index.html');
  const indexStats = await stat(frontendIndex);
  if ( ! indexStats.isFile() ) {
    throw new Error(`Frontend index not found: <${ frontendIndex }>`);
  }
  const runtimeIconPath:string | undefined = resolveRuntimeWindowIconPath();
  if ( runtimeIconPath ) {
    const iconStats = await stat(runtimeIconPath);
    if ( ! iconStats.isFile() ) {
      throw new Error(`Runtime window icon not found: <${ runtimeIconPath }>`);
    }
  }
}

function checkPortAvailability(port:number):Promise<void> {
  return new Promise((resolvePromise, rejectPromise) => {
    const server = createServer();
    server.once('error', (error:Error & { code?:string }) => {
      if ( error.code === 'EADDRINUSE' ) {
        rejectPromise(new Error(
          `Port ${ port } is already in use on ${ BACKEND_HOST }. `
          + 'Close the process that is listening on this port and restart Wiki|Docs.',
        ));
        return;
      }
      rejectPromise(error);
    });
    server.once('listening', () => {
      server.close(() => resolvePromise());
    });
    server.listen(port, BACKEND_HOST);
  });
}

async function waitForBackendReady(timeoutMs:number):Promise<void> {
  const start:number = Date.now();
  while ( Date.now() - start < timeoutMs ) {
    try {
      const response:Response = await fetch(BACKEND_HEALTHCHECK_URL, { method: 'GET' });
      if ( [204, 501].includes(response.status) ) {
        return;
      }
    } catch {
      // backend still booting
    }
    await new Promise((resolvePromise) => setTimeout(resolvePromise, 300));
  }
  throw new Error(`Backend did not become ready within ${ timeoutMs }ms`);
}

async function showBackendCrashDialogAndHandleRestart(message:string):Promise<void> {
  if ( backendCrashDialogOpen || appClosing ) {
    return;
  }
  backendCrashDialogOpen = true;
  try {
    const { response } = await dialog.showMessageBox({
      type: 'error',
      title: 'Backend stopped unexpectedly',
      message: 'The embedded backend process terminated.',
      detail: message,
      buttons: ['Restart backend', 'Close app'],
      defaultId: 0,
      cancelId: 1,
      noLink: true,
    });
    if ( response === 1 ) {
      app.quit();
      return;
    }
    await startOrCrash();
    if ( mainWindow ) {
      await mainWindow.loadURL(BACKEND_BASE_URL);
    }
  } finally {
    backendCrashDialogOpen = false;
  }
}

function stopBackendProcess():void {
  if ( backendProcess && ! backendProcess.killed ) {
    backendProcess.kill();
  }
  backendProcess = null;
}

function stopBackendProcessForRelaunch(timeoutMs = 5000):Promise<void> {
  if ( backendProcess === null || backendProcess.killed ) {
    backendProcess = null;
    return Promise.resolve();
  }
  const processToStop:ChildProcessWithoutNullStreams = backendProcess;
  return new Promise((resolvePromise, rejectPromise) => {
    let settled = false;
    const settle = (callback:() => void):void => {
      if ( settled ) {
        return;
      }
      settled = true;
      clearTimeout(timeoutHandle);
      processToStop.off('exit', onExit);
      callback();
    };
    const onExit = ():void => {
      backendProcess = null;
      settle(resolvePromise);
    };
    const timeoutHandle = setTimeout(() => {
      settle(() => {
        rejectPromise(new Error('Backend did not stop before relaunch timeout'));
      });
    }, timeoutMs);

    processToStop.once('exit', onExit);
    const signalSent:boolean = processToStop.kill();
    if ( ! signalSent ) {
      settle(() => {
        rejectPromise(new Error('Backend stop signal failed before relaunch'));
      });
    }
  });
}

async function startBackendProcess(config:RuntimeConfig, artifacts:RuntimeArtifacts):Promise<void> {
  await checkPortAvailability(BACKEND_PORT);
  const environment:NodeJS.ProcessEnv = {
    ...process.env,
    MODE: 'local',
    SECRET: config.secret,
    DATASETS: config.datasetsPath,
    PORT: String(BACKEND_PORT),
    FRONTEND: artifacts.frontendPath,
    ELECTRON_RUN_AS_NODE: '1',
  };
  backendProcess = spawn(process.execPath, [artifacts.backendEntryPath], {
    cwd: artifacts.backendWorkingDirectory,
    env: environment,
    stdio: 'pipe',
    windowsHide: true,
  });
  backendProcess.stdout.on('data', (chunk:Buffer) => {
    process.stdout.write(`[backend] ${ chunk.toString() }`);
  });
  backendProcess.stderr.on('data', (chunk:Buffer) => {
    process.stderr.write(`[backend] ${ chunk.toString() }`);
  });
  backendProcess.on('exit', (code:number | null, signal:NodeJS.Signals | null) => {
    const crashed = ! appClosing && ! appRelaunching;
    backendProcess = null;
    if ( crashed ) {
      const detail = `Exit code: ${ code ?? 'none' }, signal: ${ signal ?? 'none' }`;
      void showBackendCrashDialogAndHandleRestart(detail);
    }
  });
  await waitForBackendReady(30000);
}

async function openSettingsWindow():Promise<void> {
  if ( settingsWindow ) {
    settingsWindow.focus();
    return;
  }
  settingsWindow = new BrowserWindow({
    width: 760,
    height: 640,
    parent: mainWindow ?? undefined,
    webPreferences: {
      preload: SETTINGS_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });
  installEditableContextMenu(settingsWindow);
  settingsWindow.on('closed', () => {
    settingsWindow = null;
  });
  await settingsWindow.loadURL(SETTINGS_WINDOW_WEBPACK_ENTRY);
}

function installEditableContextMenu(targetWindow:BrowserWindow):void {
  targetWindow.webContents.on('context-menu', (_event, params) => {
    const hasSelection:boolean = params.selectionText.trim().length > 0;
    if ( ! params.isEditable && ! hasSelection ) {
      return;
    }

    const submenu:MenuItemConstructorOptions[] = params.isEditable
      ? [
        { role: 'undo' },
        { role: 'redo' },
        { type: 'separator' },
        { role: 'cut' },
        { role: 'copy' },
        { role: 'paste' },
        { role: 'selectAll' },
      ]
      : [
        { role: 'copy' },
        { role: 'selectAll' },
      ];

    Menu.buildFromTemplate(submenu).popup({ window: targetWindow });
  });
}

async function triggerManualSync():Promise<void> {
  if ( ! currentRuntimeConfig ) {
    throw new Error('Runtime configuration is not loaded');
  }
  const syncConfig:RemoteServerConfig = await readSyncConfig();
  const result = await syncOrchestrator.runSync(currentRuntimeConfig.datasetsPath, syncConfig);
  if ( result.hasChanges && mainWindow && ! mainWindow.isDestroyed() ) {
    mainWindow.webContents.reloadIgnoringCache();
  }
}

function installApplicationMenu():void {
  const syncItem:MenuItemConstructorOptions = {
    label: 'Sync Dataset',
    accelerator: process.platform === 'darwin' ? 'Cmd+Shift+S' : 'Ctrl+Shift+S',
    click: () => {
      triggerManualSync().catch((error:unknown) => {
        const dialogOwner = settingsWindow ?? mainWindow;
        const errorMessage = error instanceof Error ? error.message : String(error);
        if ( dialogOwner ) {
          void dialog.showMessageBox(dialogOwner, {
            type: 'error',
            title: 'Sync Error',
            message: 'Synchronization failed.',
            detail: errorMessage,
          });
        }
      });
    },
  };

  const settingsItem:MenuItemConstructorOptions = {
    label: 'Settings',
    accelerator: process.platform === 'darwin' ? 'Cmd+,' : 'Ctrl+,',
    click: () => {
      void openSettingsWindow();
    },
  };

  const fileMenu:MenuItemConstructorOptions = {
    label: 'File',
    submenu: [
      syncItem,
      { type: 'separator' },
      settingsItem,
      { type: 'separator' },
      process.platform === 'darwin' ? { role: 'close' } : { role: 'quit' },
    ],
  };

  const template:MenuItemConstructorOptions[] = process.platform === 'darwin'
    ? [{ role: 'appMenu' }, fileMenu, { role: 'editMenu' }]
    : [fileMenu, { role: 'editMenu' }];

  Menu.setApplicationMenu(Menu.buildFromTemplate(template));
}

function setupSyncOrchestratorEvents():void {
  syncOrchestrator.onStatusChange((status:SyncStatusState) => {
    if ( mainWindow && ! mainWindow.isDestroyed() ) {
      mainWindow.webContents.send('sync:status-changed', status);
    }
    if ( settingsWindow && ! settingsWindow.isDestroyed() ) {
      settingsWindow.webContents.send('sync:status-changed', status);
    }
  });

  syncOrchestrator.setOnSyncCompletedWithChanges(() => {
    if ( mainWindow && ! mainWindow.isDestroyed() ) {
      mainWindow.webContents.reloadIgnoringCache();
    }
  });
}

function registerSettingsAndSyncIpcHandlers():void {
  ipcMain.handle('settings:get-runtime-config', async () => {
    const configPath:string = getRuntimeConfigPath();
    const config:RuntimeConfig | null = await readRuntimeConfig(configPath);
    if ( ! config ) {
      throw new Error('Runtime config not found');
    }
    return config;
  });

  ipcMain.handle('settings:browse-datasets-path', async () => {
    const dialogOwner = settingsWindow ?? mainWindow;
    const openDialogOptions:OpenDialogOptions = {
      title: 'Select DATASETS directory',
      buttonLabel: 'Use this directory',
      properties: ['openDirectory'],
    };
    const selection = dialogOwner
      ? await dialog.showOpenDialog(dialogOwner, openDialogOptions)
      : await dialog.showOpenDialog(openDialogOptions);
    if ( selection.canceled || selection.filePaths.length === 0 ) {
      return null;
    }
    return selection.filePaths[ 0 ];
  });

  ipcMain.handle('settings:save-runtime-config', async (_event, payload:unknown):Promise<SaveRuntimeConfigResult> => {
    if ( typeof payload !== 'object' || payload === null ) {
      throw new Error('Invalid settings payload');
    }
    const candidate:Record<string, unknown> = payload as Record<string, unknown>;
    if ( typeof candidate.datasetsPath !== 'string' ) {
      throw new Error('Invalid datasetsPath value');
    }
    if ( typeof candidate.secret !== 'string' ) {
      throw new Error('Invalid secret value');
    }

    const nextConfig:RuntimeConfig = await normalizeAndValidateRuntimeConfig({
      datasetsPath: candidate.datasetsPath,
      secret: candidate.secret,
    });

    const dialogOwner = settingsWindow ?? mainWindow;
    const messageBoxOptions = {
      type: 'question' as const,
      title: 'Save settings',
      message: 'Saving settings requires a full application relaunch.',
      detail: 'Do you want to save and relaunch Wiki|Docs now?',
      buttons: ['Save and relaunch', 'Cancel'],
      defaultId: 0,
      cancelId: 1,
      noLink: true,
    };
    const { response } = dialogOwner
      ? await dialog.showMessageBox(dialogOwner, messageBoxOptions)
      : await dialog.showMessageBox(messageBoxOptions);

    if ( response === 1 ) {
      return { status: 'cancelled' };
    }

    await writeRuntimeConfig(getRuntimeConfigPath(), nextConfig);
    appRelaunching = true;
    await stopBackendProcessForRelaunch();
    app.relaunch();
    app.quit();
    return { status: 'relaunching' };
  });

  ipcMain.handle('sync:get-config', async () => {
    return await readSyncConfig();
  });

  ipcMain.handle('sync:save-config', async (_event, payload:RemoteServerConfig) => {
    await writeSyncConfig(payload);
    const cachedSyncConfig:RemoteServerConfig = payload;
    syncOrchestrator.configureAutoSync(
      () => currentRuntimeConfig?.datasetsPath ?? null,
      () => cachedSyncConfig,
    );
  });

  ipcMain.handle('sync:start', async () => {
    await triggerManualSync();
  });

  ipcMain.handle('sync:get-status', async () => {
    return syncOrchestrator.getStatus();
  });
}

async function startOrCrash():Promise<void> {
  currentRuntimeConfig = await ensureRuntimeConfigOrPrompt();
  const artifacts:RuntimeArtifacts = resolveRuntimeArtifacts();
  await ensureRuntimeArtifactsPresent(artifacts);
  await startBackendProcess(currentRuntimeConfig, artifacts);

  const syncConfig:RemoteServerConfig = await readSyncConfig();
  syncOrchestrator.configureAutoSync(
    () => currentRuntimeConfig?.datasetsPath ?? null,
    () => syncConfig,
  );
}

function createMainWindow():BrowserWindow {
  const iconPath:string | undefined = resolveRuntimeWindowIconPath();
  const browserWindow = new BrowserWindow({
    height: 900,
    width: 1280,
    autoHideMenuBar: process.platform !== 'darwin',
    ...( iconPath ? { icon: iconPath } : {} ),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });
  browserWindow.on('closed', () => {
    if ( mainWindow === browserWindow ) {
      mainWindow = null;
    }
  });
  return browserWindow;
}

async function bootstrap():Promise<void> {
  await startOrCrash();
  mainWindow = createMainWindow();
  await mainWindow.loadURL(BACKEND_BASE_URL);
}

app.on('ready', async () => {
  setupSyncOrchestratorEvents();
  registerSettingsAndSyncIpcHandlers();
  installApplicationMenu();
  try {
    await bootstrap();
  } catch ( error ) {
    dialog.showErrorBox(
      'Startup failed',
      error instanceof Error ? error.message : String(error),
    );
    app.quit();
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if ( process.platform !== 'darwin' ) {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if ( BrowserWindow.getAllWindows().length === 0 && ! appClosing ) {
    mainWindow = createMainWindow();
    void mainWindow.loadURL(BACKEND_BASE_URL);
  }
});

app.on('before-quit', () => {
  appClosing = true;
  syncOrchestrator.stopAutoSync();
  stopBackendProcess();
});
